### ISSUE TITLE
Deprecation warning on `auto-correct`

### ISSUE THREAD

**Issue by eirvandelden** [nova-ruby/solargraph#2]
Seen in the logs:
```
Solargraph[21:43:26.716000] --auto-correct is deprecated; use --autocorrect instead.
```

**Comment by tommasongr** [comment]
Hi @eirvandelden!

I confirm that solargraph `v0.48.0` logs this warning on formatting. However `v0.49.0` fixed it.

Since the extension has never sent the `--auto-correct` flag I guess it was a solargraph issue. Probably related to a newer Rubucop version. Try to upgrade and let me know 😉

Anyway sorry for the late reply... 😥
